### ISSUE TITLE
"Fantasy" font requires a license

### ISSUE THREAD

**Issue by bchavet** [jillmoreno/jilliennemoreno.com#7]
The "Fantasy" font used for the `my-name` class is licensed for desktop use only. Another font should be chosen for this.

https://fonts.google.com

**Comment by jillmoreno** [comment]
I changed it to Bradley Hand and pushed the change to Master....let me know if that one also has an issue?

**Comment by bchavet** [comment]
This one? https://www.fonts.com/font/itc/itc-bradley-hand?QueryFontType=Web&src=GoogleWebFonts
